version: 2
jobs:
  build-server:
    docker:
      - image: circleci/node:8.9
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: echo "npm installing on server"
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
  build-client:
    docker:
      - image: circleci/node:12.16.3-browsers
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            - v1-dependencies-
      - run: echo "npm installing client side"
      - run: cd client && yarn install
      - run: cd client && yarn build
      - save_cache:
          paths:
            - client/node_modules
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "client/package.json" }}
  test-client:
    docker:
      - image: circleci/node:12.16.3-browsers
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            - v1-dependencies-
      - run: echo "npm testing client side"
      - run: cd client && yarn install
      - run: cd client && yarn test
      - save_cache:
          paths:
            - client/node_modules
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "client/package.json" }}
workflows:
  version: 2
  build_test:
    jobs:
      - build-server
      - build-client
      - test-client
