version: 2
jobs:
  build-server:
    docker:
      - image: circleci/node:8.9
    parallelism: 4
    steps:
      - checkout
      - run: echo "npm installing on server"
      - run: npm install
  build-client:
    docker:
      - image: circleci/node:12.16.3-browsers
    parallelism: 4
    steps:
      - checkout
      - run: echo "npm installing react"
      - run: cd client && yarn install
      - run: CI=true yarn build
  test-client:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run: echo "testing react"
      - run: npm run test-client
workflows:
  build_test:
    jobs:
      - build-server
      - build-client
      - test-client
      - test:
          requires:
            - build-client
